script: "LD_LIBRARY_PATH=lib bundle exec rake ci"

rvm:
  - 2.0.0
  - ruby-head
  - jruby
  - jruby-head
  - rbx-19mode

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-19mode

notifications:
  irc: "irc.freenode.org#cryptosphere"
