script: 'LD_LIBRARY_PATH=lib bundle exec rake ci'

rvm:
  - 2.0.0
  - 2.1.1
  - ruby-head
  - jruby
  - jruby-head
  - rbx-2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2

notifications:
  irc: 'irc.freenode.org#cryptosphere'
