[package]
name = "confusion"
version = "0.0.1"
authors = ["Tony Arcieri <bascule@gmail.com>"]

[dependencies.iron]
git = "https://github.com/iron/iron.git"

[dependencies.static_file]
git = "https://github.com/tarcieri/static-file.git"
